"""add is_admin field to usuarios

Revision ID: ef7e6b1dddce
Revises: 20260222_01
Create Date: 2026-02-22 14:46:35.617076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7e6b1dddce'
down_revision: Union[str, Sequence[str], None] = '20260222_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_egresos_usuario_id'), table_name='egresos', if_exists=True)
    op.create_index(op.f('ix_egresos_id'), 'egresos', ['id'], unique=False)
    op.drop_constraint(op.f('egresos_usuario_id_fkey'), 'egresos', type_='foreignkey')
    op.create_foreign_key(None, 'egresos', 'usuarios', ['usuario_id'], ['id'])
    
    # Añadir is_admin como nullable primero
    op.add_column('usuarios', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # Actualizar todos los usuarios existentes a False
    op.execute("UPDATE usuarios SET is_admin = FALSE WHERE is_admin IS NULL")
    # Ahora hacerla NOT NULL
    op.alter_column('usuarios', 'is_admin', nullable=False)
    
    op.drop_index(op.f('idx_usuarios_email'), table_name='usuarios', if_exists=True)
    op.drop_constraint(op.f('usuarios_email_key'), 'usuarios', type_='unique', if_exists=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_unique_constraint(op.f('usuarios_email_key'), 'usuarios', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_usuarios_email'), 'usuarios', ['email'], unique=False)
    op.drop_column('usuarios', 'is_admin')
    op.drop_constraint(None, 'egresos', type_='foreignkey')
    op.create_foreign_key(op.f('egresos_usuario_id_fkey'), 'egresos', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_egresos_id'), table_name='egresos')
    op.create_index(op.f('idx_egresos_usuario_id'), 'egresos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###
